import { createContext, useContext, useEffect, useState, useCallback } from 'react'
import { supabase } from '../lib/supabase.js'

const AuthContext = createContext(null)

function isAutoGeneratedUsername(username, email) {
  if (!username || !email) return true
  if (username.startsWith('user_')) return true
  const prefix = email.split('@')[0]?.toLowerCase()
  return username.toLowerCase() === prefix
}

export function AuthProvider({ children }) {
  const [session, setSession] = useState(undefined)
  const [user, setUser] = useState(null)
  const [profile, setProfile] = useState(undefined)

  const fetchProfile = useCallback(async (authUser) => {
    if (!authUser?.id) { setProfile(null); return }

    // Use maybeSingle to avoid error when row doesn't exist
    const { data, error } = await supabase
      .from('users')
      .select('id, username, is_admin')
      .eq('id', authUser.id)
      .maybeSingle()

    if (error) {
      console.warn('Profile fetch error:', error.message)
      setProfile(null)
      return
    }

    if (!data) {
      // Profile row missing — create it (trigger may have failed)
      console.log('Creating missing profile for:', authUser.id)
      const fallbackUsername = authUser.user_metadata?.username || authUser.email?.split('@')[0] || `user_${authUser.id.slice(0, 6)}`
      const { data: newRow } = await supabase
        .from('users')
        .upsert({ id: authUser.id, username: fallbackUsername }, { onConflict: 'id' })
        .select('id, username, is_admin')
        .single()
      setProfile(newRow ?? { id: authUser.id, username: fallbackUsername })
      return
    }

    setProfile(data)
  }, [])

  useEffect(() => {
    supabase.auth.getSession().then(({ data: { session } }) => {
      setSession(session)
      setUser(session?.user ?? null)
      if (session?.user) fetchProfile(session.user)
      else setProfile(null)
    })

    const { data: { subscription } } = supabase.auth.onAuthStateChange((_event, session) => {
      setSession(session)
      setUser(session?.user ?? null)
      if (session?.user) fetchProfile(session.user)
      else setProfile(null)
    })

    return () => subscription.unsubscribe()
  }, [fetchProfile])

  async function signIn(email, password) {
    const { error } = await supabase.auth.signInWithPassword({ email, password })
    if (error) throw error
  }

  async function signUp(email, password, username) {
    // Check username uniqueness before creating auth account
    if (username) {
      const { data: existing } = await supabase.from('users').select('id').ilike('username', username.trim()).maybeSingle()
      if (existing) throw new Error('Username already taken')
    }
    const { data, error } = await supabase.auth.signUp({
      email, password,
      options: { data: { username: username?.trim() || undefined } },
    })
    if (error) throw error
    return data // caller can check data.session for email confirmation
  }

  async function saveUsername(username) {
    if (!user) throw new Error('Not authenticated')
    const trimmed = username.trim()
    // Try update first, then insert if row doesn't exist
    const { data: updated } = await supabase.from('users').update({ username: trimmed }).eq('id', user.id).select('id').maybeSingle()
    if (!updated) {
      const { error: insErr } = await supabase.from('users').insert({ id: user.id, username: trimmed })
      if (insErr) throw insErr
    }
    setProfile((prev) => ({ ...prev, id: user.id, username: trimmed }))
  }

  function needsUsername() {
    if (profile === undefined) return false
    if (!profile?.username) return true
    return isAutoGeneratedUsername(profile.username, user?.email)
  }

  async function signOut() {
    await supabase.auth.signOut()
    setProfile(null)
  }

  return (
    <AuthContext.Provider value={{ session, user, profile, signIn, signUp, signOut, saveUsername, needsUsername, refreshProfile: () => fetchProfile(user) }}>
      {children}
    </AuthContext.Provider>
  )
}

export function useAuth() {
  return useContext(AuthContext)
}
