import { createContext, useContext, useEffect, useState, useCallback } from 'react'
import { supabase } from '../lib/supabase.js'

const AuthContext = createContext(null)

/**
 * Returns true if the username looks auto-generated from an email prefix.
 * The DB trigger typically sets username = email part before @.
 */
function isAutoGeneratedUsername(username, email) {
  if (!username || !email) return true
  const emailPrefix = email.split('@')[0]?.toLowerCase()
  return username.toLowerCase() === emailPrefix
}

export function AuthProvider({ children }) {
  const [session, setSession] = useState(undefined) // undefined = loading
  const [user, setUser] = useState(null)
  const [profile, setProfile] = useState(undefined) // undefined = loading, null = not found

  const fetchProfile = useCallback(async (userId) => {
    if (!userId) { setProfile(null); return }
    const { data, error } = await supabase
      .from('users')
      .select('id, username, is_admin')
      .eq('id', userId)
      .single()
    if (error || !data) {
      setProfile(null)
    } else {
      setProfile(data)
    }
  }, [])

  useEffect(() => {
    supabase.auth.getSession().then(({ data: { session } }) => {
      setSession(session)
      setUser(session?.user ?? null)
      if (session?.user) fetchProfile(session.user.id)
      else setProfile(null)
    })

    const { data: { subscription } } = supabase.auth.onAuthStateChange((_event, session) => {
      setSession(session)
      setUser(session?.user ?? null)
      if (session?.user) fetchProfile(session.user.id)
      else setProfile(null)
    })

    return () => subscription.unsubscribe()
  }, [fetchProfile])

  async function signIn(email, password) {
    const { error } = await supabase.auth.signInWithPassword({ email, password })
    if (error) throw error
  }

  async function signUp(email, password, username) {
    const { error } = await supabase.auth.signUp({
      email,
      password,
      options: { data: { username: username?.trim() || undefined } },
    })
    if (error) throw error
  }

  async function saveUsername(username) {
    if (!user) throw new Error('Not authenticated')
    const { error } = await supabase
      .from('users')
      .update({ username: username.trim() })
      .eq('id', user.id)
    if (error) throw error
    setProfile((prev) => ({ ...prev, id: user.id, username: username.trim() }))
  }

  /**
   * True when the user needs to pick a proper username before using the app.
   * Covers: no profile row, null username, or auto-generated email-prefix username.
   */
  function needsUsername() {
    if (profile === undefined) return false // still loading
    if (!profile?.username) return true
    return isAutoGeneratedUsername(profile.username, user?.email)
  }

  async function signOut() {
    await supabase.auth.signOut()
    setProfile(null)
  }

  return (
    <AuthContext.Provider value={{
      session,
      user,
      profile,
      signIn,
      signUp,
      signOut,
      saveUsername,
      needsUsername,
      refreshProfile: () => fetchProfile(user?.id),
    }}>
      {children}
    </AuthContext.Provider>
  )
}

export function useAuth() {
  return useContext(AuthContext)
}
